# Generated by Django 3.0 on 2021-09-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='qr_code',
            new_name='qr_code_image',
        ),
    ]
