# Generated by Django 3.0 on 2021-09-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_attributes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
